#!/bin/bash

executable="./smpl"

totalpassed=0
totalfailed=0
for i in 1 2 3 4 5 6 7 8 9 10
do
	prog="pr$i.cql"
	passed=0
	
	for j in 1 2 3 4 5
	do 
		testdir="./pr"
		testdir+=$i
		testdir+="/"
		testdir+="test"
		testdir+=$j
		#testdir+="/"
		out="youroutput.csv"

		cp $executable $testdir
		cp $prog $testdir 
		cd $testdir 
	
	    #timeout 10s 
	    $executable $prog > $out 2>/dev/null

		if [ "$?" = 124 ]; then
			echo -e "  TEST FAILED -- TIMEOUT"
		else
			outofficial="out.csv" 

		diff -wB $out $outofficial > /dev/null
		if [ "$?" = 0 ]; then
			passed=$((passed+1))
		else
			totalfailed=$((totalfailed+1))
			echo -e "[FAILED] pr$i test $j" 
			echo 
			fi
		fi
		rm $executable 
		rm $prog
		rm $out
		cd ../..
	done 
	totalpassed=$((totalpassed+passed))
done
echo
echo "$totalpassed tests passed in total out of $((totalpassed+totalfailed))"
if [ "$totalfailed" != 0 ]; then
	exit 1
fi
